### ISSUE TITLE
Adjust interaction Rate to system or propose option

### ISSUE THREAD

**Issue by sawenzel** [AliceO2Group/O2DPG#49]
The interaction rate needs to be settable or determined from the collision system.
(But I think that it is dynamic and not always at 50kHz peak even for PbPb).

**Comment by sawenzel** [comment]
@gconesab : Could you take a look?

**Comment by gconesab** [comment]
I can include a settable parameter, no problem. Just tell me how this is set in O2 and what are the roughly expected rates in the different collision systems if you have it at hand.

**Comment by sawenzel** [comment]
PbPb : 50kHz
pp : 400kHz

**Comment by sawenzel** [comment]
Actually we must also foresee to fetch the interaction rate from CCDB as it various quite a lot during a "fill". This will play a role in productions anchored to a specific timeframe.

**Comment by gconesab** [comment]
I committed yesterday the change to have this option, https://github.com/AliceO2Group/O2DPG/pull/51, have a look and let me know if something else is needed.
